version: 0.2

phases:

    install: 
        commands:
            - go get -u golang.org/x/lint/golint

    pre_build: 
        commands:
            - go get ./...
            - golint -set_exit_status

    build:
        commands:
            - go build main.go

artifacts:

    files:
        - "**/*"
